name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: git clone https://github.com/TeamFlos/phira --depth 1 -b render
    - name: Build
      run: |
        cd phira
        sudo apt-get install libgdk-pixbuf-2.0-dev libatk1.0-dev -y
        sudo apt update && sudo apt install -y build-essential pkg-config libgtk-3-dev libgdk-pixbuf2.0-dev libpango1.0-dev libcairo2-dev libavcodec-dev libavformat-dev libswscale-dev libjpeg-turbo8-dev libpng-dev libtiff-dev libatk1.0-dev libgstreamer-plugins-base1.0-dev libcurl4-openssl-dev libsqlite3-dev libmysqlclient-dev postgresql-contrib libicu-dev
        cargo build -r --bin phira-render --target x86_64-unknown-linux-gnu
    - uses: actions/upload-artifact@v3.2.1-node20
      with:
        path: phira/target
