name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: git clone https://github.com/364hao/phira.git --depth 1 -b render
    - name: Build
      run: |
        cd phira
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev libasound2-dev libssl-dev pkg-config
        cargo build -r --bin phira-render --target x86_64-unknown-linux-gnu
    - uses: actions/upload-artifact@v3.2.1-node20
      with:
        path: phira/target
