name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: 3.12.0
    - name: Clone Project
      run: |
        git clone https://github.com/westhecool/python-apkpure.git --depth 1
        git clone https://github.com/364hao/Phigros_Resource.git --depth 1
        git clone https://github.com/364hao/PhigrosPlayer.git --depth 1
    - name: Get Phigros Apk
      run: |
        python -m pip install --upgrade pip
        cd python-apkpure
        python -m pip install -r requirements.txt
        python cli.py download com.PigeonGames.Phigros --output-file Phigros.xapk
        ls
    - name: Extra Apk
      uses: TheDoctor0/zip-release@0.7.6
      with:
        filename: Phigros.xapk
        path: ./python-apkpure
        directory: ./Phigros_Resource
    - name: Release Assests
      run: |
        cd Phigros_Resource
        ls
        python -m pip install UnityPy fsb5 rich
        python gameInformation.py com.PigeonGames.Phigros.apk
        python resource.py ./Android/obb/com.PigeonGames.Phigros/main.112.com.PigeonGames.Phigros.obb
        python phira.py
        ls
    - name: Generate video 
      run: |
        cd PhigrosPlayer
        python -m pip install -r requirements.txt
        
