name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5.2.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/westhecool/python-apkpure.git @ main # 克隆并安装该repo
    - name: Run tests
      run: |
        python cli.py
