name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5.2.0
    - name: Clone Project
      run: |
        git clone https://github.com/westhecool/python-apkpure.git --depth 1
        git clone https://github.com/364hao/Phigros_Resource.git --depth 1
    - name: Get Phigros Apk
      run: |
        sudo python -m pip install --upgrade pip
        cd python-apkpure
        sudo python -m pip install -r requirements.txt
        python cli.py download com.PigeonGames.Phigros --output-file Phigros.xapk
        ls
    - name: Extra Apk
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq ./python-apkpure/Phigros.xapk -d ./Phigros_Resource
    - name: Release Assests
      run: |
        cd Phigros_Resource
        ls
        sudo python -m pip install -r requirements.txt
        python gameInformation.py com.PigeonGames.Phigros.apk
        python resource.py ./Android/obb/com.PigeonGames.Phigros/main.112.com.PigeonGames.Phigros.obb
        python phira.py
      
