name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5.2.0
    - name: Set up Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: x86_64-unknown-linux-gnu
        components: rustfmt, clippy
    - name: Clone Project
      run: |
        git clone https://github.com/westhecool/python-apkpure.git --depth 1
        git clone https://github.com/364hao/Phigros_Resource.git --depth 1
        git clone https://github.com/Ivan-1F/phichain.git --depth 1
    - name: Build Phichain
      run: |
        cd phichain
        cargo build -p phichain-converter --release --target x86_64-unknown-linux-gnu
        mv phichain/target/x86_64-pc-windows-gnu/release/phichain-converter ../phichain-converter
      env:
        RUST_BACKTRACE: 1
    - name: Download Phigros Package
      run: |
        cd python-apkpure
        python -m pip install -r requirements.txt
        python cli.py download com.PigeonGames.Phigros --output-file Phigros.xapk
    - name: Extra Phigros Package
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: python-apkpure/Phigros.xapk
        pathTarget: Phigros_Resource
    - name: Release Assests
      run: |
        cd Phigros_Resource
        python -m pip install UnityPy~=1.10.14 fsb5 rich
        python gameInformation.py com.PigeonGames.Phigros.apk
        python resource.py Android/obb/com.PigeonGames.Phigros
      env:
        PYTHONIOENCODING: utf-8
    - name: Convert Charts
      run: |
        python ChartConverter.py
      env:
        PYTHONIOENCODING: utf-8
    - name: Generate Phira Charts
      run: |
        cd Phigros_Resource
        python phira.py --phira
      env:
        PYTHONIOENCODING: utf-8
    - name: Generate Phichain Charts
      run: |
        python ChartPcTs.py
      env:
        PYTHONIOENCODING: utf-8
    - name: Delete Release
      uses: sgpublic/delete-release-action@v1.2
      with:
        repo: "${{ github.repository }}"
        release-drop: true
        release-keep-count: 0
        release-drop-tag: true
        pre-release-drop: false
        draft-drop: true
        draft-drop-count: -1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}