name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: 3.12.6
    - name: Clone Project
      run: |
        git clone https://github.com/westhecool/python-apkpure.git --depth 1
        git clone https://github.com/364hao/Phigros_Resource.git --depth 1
        curl -L -o phira-render.zip https://github.com/364hao/Test/releases/download/ActionTools/phira-render.zip
        curl -L -o phichain-converter.exe https://github.com/364hao/Test/releases/download/ActionTools/phichain-converter.exe
    - name: Get Phigros Apk
      run: |
        python -m pip install --upgrade pip
        cd python-apkpure
        python -m pip install -r requirements.txt
        python cli.py download com.PigeonGames.Phigros --output-file Phigros.xapk
        ls
    - name: Extra Apk
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: .\\python-apkpure/Phigros.xapk
        pathTarget: .\\Phigros_Resource
    - name: Release Assests
      run: |
        cd Phigros_Resource
        ls
        python -m pip install UnityPy fsb5 rich
        python gameInformation.py com.PigeonGames.Phigros.apk
        python resource.py ".\\Android\\obb\\com.PigeonGames.Phigros"
        python phira.py --rpe
        ls
        ls phira\\AT
      env:
        PYTHONIOENCODING: utf-8
    - name: Test
      run: |
        curl -L -o phichain-converter.exe https://github.com/364hao/Test/releases/download/ActionTools/phichain-converter.exe
        ls
        D:\\a\\Test\\Test\\phichain-converter.exe phira\\AT\\INFiNiTEENERZYOverdoze.RekuMochizuki-AT.pez
    - name: Delete Release
      uses: sgpublic/delete-release-action@v1.2
      with:
        repo: "${{ github.repository }}"
        release-drop: true
        release-keep-count: 0
        release-drop-tag: true
        pre-release-drop: false
        draft-drop: true
        draft-drop-count: -1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Convert Charts
      run: |
        ls
        python ChartConverter.py
      env:
        PYTHONIOENCODING: utf-8
    - name: Render Charts
      run: |
        unzip phira-render.zip
        ls
        python ChartRenderer.py
      env:
        PYTHONIOENCODING: utf-8
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RenderCharts
        path: |
          Phigros_Resource