name: Run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Sync_Data:
    runs-on: windows-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v4
    - run: |
        git clone https://github.com/westhecool/python-apkpure.git --depth 1
        git clone https://github.com/364hao/Phigros_Resource.git --depth 1
        git clone https://github.com/Ivan-1F/phichain.git --depth 1
    - name: Set up Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: x86_64-pc-windows-msvc
        components: rustfmt, clippy
    - name: Build Phichain
      run: |
        cd phichain
        cargo build -p phichain-converter --release --target x86_64-pc-windows-msvc
        move target/x86_64-pc-windows-msvc/release/phichain-converter.exe ../phichain-converter.exe
      env:
        RUST_BACKTRACE: 1
    - name: Download Phigros Package
      run: |
        cd python-apkpure
        python -m pip install -r requirements.txt
        python cli.py download com.PigeonGames.Phigros --output-file Phigros.xapk
    - name: Extra Phigros Package
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: python-apkpure/Phigros.xapk
        pathTarget: Phigros_Resource
    - name: Release Assests
      run: |
        cd Phigros_Resource
        python -m pip install UnityPy==1.10.18 fsb5 rich
        python gameInformation.py com.PigeonGames.Phigros.apk
        python resource.py Android/obb/com.PigeonGames.Phigros
      env:
        PYTHONIOENCODING: utf-8
    - name: Convert Charts
      run: |
        python ChartConverter.py
        python ChartPcTs.py
      env:
        PYTHONIOENCODING: utf-8
    - name: Generate Phira Charts
      run: |
        cd Phigros_Resource
        python phira.py --phira
      env:
        PYTHONIOENCODING: utf-8
    - name: Delete Release
      uses: sgpublic/delete-release-action@v1.2
      with:
        release-drop: true
        release-keep-count: -1
        pre-release-drop: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}