name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5.2.0
    - name: Clone Apkpure-python
      run: |
        git clone https://github.com/westhecool/python-apkpure.git --depth 1
    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip
        cd python-apkpure
        sudo python -m pip install -r requirements.txt
    - name: Get Phigros Apk
      run: |
        cd python-apkpure
        python cli.py download com.PigeonGames.Phigros 
        ls
      
