name: GitHub CLI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 执行需要认证的操作
    - name: Create Release and Upload Assets
      run: |
        gh release create v1.0.0 --title "Version 1.0.0" --notes "Initial release"
