name: Run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: write-all

jobs:
  Sync_Data:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v4
    - uses: FedericoCarboni/setup-ffmpeg@v3
    - name: Download Tools
      run: |
        curl -L -o phichain.zip https://github.com/364hao/Test/releases/download/phichain/phichain-v0.4.1+build.383-x86_64-unknown-linux-gnu.zip
        unzip phichain.zip 
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12.6'
    - run: |
        git clone https://github.com/westhecool/python-apkpure.git --depth 1
        git clone https://github.com/364hao/Phigros_Resource.git --depth 1
    - name: Download Phigros Package
      run: |
        cd python-apkpure
        pip install --upgrade pip
        pip install -r requirements.txt
        python cli.py download com.PigeonGames.Phigros --output-file Phigros.xapk
    - name: Extra Phigros Package
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: python-apkpure/Phigros.xapk
        pathTarget: Phigros_Resource
    - name: Release Assests
      run: |
        cd Phigros_Resource
        sudo apt install libogg-dev libvorbis-dev -y
        pip install UnityPy==1.10.18 fsb5 rich==13.8.1
        python gameInformation.py com.PigeonGames.Phigros.apk
        python resource.py Android/obb/com.PigeonGames.Phigros
        python phira.py
      env:
        PYTHONIOENCODING: utf-8
    - name: Convert Charts
      run: |
        python ChartConvert.py
        python PhichainMove.py
      env:
        PYTHONIOENCODING: utf-8
    - name: Render Charts
      run: |
        sudo apt install -y libgtk-3-dev libgdk-pixbuf2.0-dev
        sudo apt-get install -y xvfb
        sudo apt install -y x11vnc
        sudo apt-get install libxkbcommon-x11-0 -y
        Xvfb :1 -screen 0 1024x768x24 > /dev/null 2>&1 &
        python RenderChart.py
      env:
        PYTHONIOENCODING: utf-8
        DISPLAY: :1
    - name: Generate Sound Effect
      run: |
        pip install -r requirements.txt
        python applyAudio.py
      env:
        PYTHONIOENCODING: utf-8
        DISPLAY: :1
    - name: Upload Assests
      uses: actions/upload-artifact@v4.4.0
      with:
        path: |
          ./PhichainProject
          ./Phigros_Resource